name: CI

on:
  pull_request:

jobs:
#  checkstyle:
#    name: Checkstyle
#    runs-on: ubuntu-latest
#    container:
#      image: registry.altlinux.org/sisyphus/alt:latest
#
#    steps:
#      - name: Install build dependencies
#        run: |
#          apt-get update
#          apt-get install -y \
#            glibc-pthread \
#            git \
#            java-11-openjdk-devel
#      - uses: actions/checkout@v4
#
#      - name: Run checkstyle check
#        run: ./gradlew checkstyle -Djava11
#
#  publishing:
#    name: Publishing (JDK ${{ matrix.java }})
#    runs-on: ubuntu-latest
#    container:
#      image: registry.altlinux.org/sisyphus/alt:latest
#    needs: checkstyle
#    strategy:
#      matrix:
#        java: [11, 17]
#
#    steps:
#      - name: Install build dependencies
#        run: |
#          apt-get update
#          apt-get install -y \
#            glibc-pthread \
#            git
#          if [ "${{ matrix.java }}" = "11" ]; then
#            apt-get install -y java-11-openjdk-devel
#          else
#            apt-get install -y java-17-openjdk-devel
#          fi
#
#      - uses: actions/checkout@v4
#
#      - name: Publish to Maven Local (JDK ${{ matrix.java }})
#        run: |
#          if [ "${{ matrix.java }}" = "11" ]; then
#            ./gradlew publishToMavenLocal -Djava11
#          else
#            ./gradlew publishToMavenLocal
#          fi
#
#  tests:
#    name: Tests (JDK ${{ matrix.java }})
#    runs-on: ubuntu-latest
#    container:
#      image: registry.altlinux.org/sisyphus/alt:latest
#    needs: publishing
#    strategy:
#      matrix:
#        java: [11, 17]
#
#    steps:
#      - name: Install build dependencies
#        run: |
#          apt-get update
#          apt-get install -y \
#            glibc-pthread \
#            git \
#            google-gson \
#            maven-lib \
#            shadow-gradle-plugin
#          if [ "${{ matrix.java }}" = "11" ]; then
#            apt-get install -y java-11-openjdk-devel
#          else
#            apt-get install -y java-17-openjdk-devel
#          fi
#
#      - uses: actions/checkout@v4
#
#      - name: Check (JDK 11)
#        if: matrix.java == 11
#        run: |
#          ./gradlew build \
#            -Djava.library.dir="/usr/share/java" \
#            -Dmaven.poms.dir="/usr/share/maven-poms" \
#            -Djava11 \
#            --info
#
#      - name: Check (JDK 17)
#        if: matrix.java != 11
#        run: |
#          ./gradlew build \
#            -Djava.library.dir="/usr/share/java" \
#            -Dmaven.poms.dir="/usr/share/maven-poms" \
#            --info

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    container:
      image: registry.altlinux.org/sisyphus/alt:latest
#    needs: tests

    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y \
            glibc-pthread \
            git \
            google-gson \
            maven-lib \
            shadow-gradle-plugin \
            java-17-openjdk-devel

      - uses: actions/checkout@v4

      - name: Run jacoco check
        run: |
          ./gradlew build \
            jacocoTestReport \
            -Djava.library.dir="/usr/share/java" \
            -Dmaven.poms.dir="/usr/share/maven-poms"

      - name: Add coverage to PR
        id: jacoco
        uses: ALonelyDuck/jacoco-report@v1.2
        with:
            paths: |
              ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 80
            min-coverage-changed-files: 80
            title: Code Coverage
#            update-comment: true
            debug-mode: true

      - name: Fail PR if change coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-changed-percentage < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: core.setFailed('Coverage of changed files is less than 80%!')

      # TODO improve code coverage to 80% and create step that fails PR lesser than 80% coverage-overall